name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting and goodbye
        run: |
          echo "Hello World!"
          echo "Done - bye!"
